services:
  mysql:
    image: mysql:8.0
    container_name: mysql8_local
    environment:
      MYSQL_ROOT_PASSWORD: z*46SVtr
      MYSQL_DATABASE: test_lab
    ports:
      - "2801:3306"
    volumes:
      - mysql8_data:/var/lib/mysql
    networks:
      - mysql8_network

volumes:
  mysql8_data:

networks:
  mysql8_network:
    driver: bridge
