version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "9728:80"
    volumes:
      - ../../nginx-server/idefl/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../nginx-server/idefl/static:/usr/share/nginx/html
    depends_on:
      - spring-app
    deploy:
      resources:
        limits:
          memory: 512M

  spring-app:
    image: openjdk:17-jdk-slim
    ports:
      - "8080:8080"
    volumes:
      - ../../nginx-server/idefl:/app/idefl
      - ../../nginx-server/idefl/app.jar:/app/app.jar
      - /Users/antoniohuertareyes/MegaSync/Develop/environments/credentials/neurovision-credentials.json:/app/idefl/credentials.json
    command: ["java", "-jar", "/app/app.jar"]
    env_file:
      - ../../nginx-server/idefl/.env
    environment:
      JAVA_OPTS: "-Xmx1536m -Xms512m"
    deploy:
      resources:
        limits:
          memory: 2G
